import pandas as pd

df = pd.read_excel(r"C:\Users\Yashs\Downloads\Dataset for Data Analytics (2).xlsx")
print(df.head())
print("-----------------------------------------------------")
print("\nShape:")
print(df.shape)
print("-----------------------------------------------------")
print("\nColumns:")
print(df.columns)
print("-----------------------------------------------------")
print("\nData Types:")
print(df.dtypes)
print("-----------------------------------------------------")
print("\nDataset Info:")
print(df.info())
print("-----------------------------------------------------")
print(df.isnull().sum())
print("Duplicate Rows =", df.duplicated().sum())
df = df.drop_duplicates()
df['Date'] = pd.to_datetime(df['Date'])
print(df.info())
print("-----------------------------------------------------")
print(df.describe())
print("-----------------------------------------------------")
print(df['Product'].value_counts())
print("-----------------------------------------------------")
print(df['OrderStatus'].value_counts())
print("-----------------------------------------------------")
print(df['PaymentMethod'].value_counts())
print("-----------------------------------------------------")
print("Total Revenue =", df['TotalPrice'].sum())
print("-----------------------------------------------------")

import matplotlib.pyplot as plt

df['Product'].value_counts().plot(kind='bar',color = ['red','orange','yellow','green','cyan','blue','violet'])
plt.title("Product Sales")
plt.xticks(rotation=45)
plt.show()

df['PaymentMethod'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Payment Methods")
plt.ylabel("")
plt.show()

df['Month'] = df['Date'].dt.month
monthly = df.groupby('Month')['TotalPrice'].sum()
monthly.plot(marker='o')
plt.title("Monthly Revenue")
plt.show()
